package io.levelops.commons.faceted_search.db.models.workitems;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.levelops.commons.faceted_search.db.models.EsIntegrationUser;
import io.levelops.commons.jackson.DefaultObjectMapper;
import io.levelops.commons.utils.ResourceUtils;
import org.assertj.core.api.Assertions;
import org.junit.Test;

import java.io.IOException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public class EsWorkItemTest {
    private static final ObjectMapper MAPPER = DefaultObjectMapper.get();

    @Test
    public void testDeserialize() throws IOException {
        String resource = ResourceUtils.getResourceAsString("workitems/workitem_es.json");
        EsWorkItem actual = MAPPER.readValue(resource, EsWorkItem.class);
        EsWorkItem expected = EsWorkItem.builder()
                .id(UUID.fromString("dd75ef24-f94b-4865-8143-1f830d5d54fd"))
                .workitemId("240")
                .integrationId(1723)
                .isActive(true)
                .summary("task-2_11")
                .project("Agile-Project")
                .status("done")
                .statusCategory("Completed")
                .workItemType("task")
                .parentWorkItemId("243")
                .priority("2")
                .assignee(EsIntegrationUser.builder()
                        .id("c7423dfe-b3ec-461e-9b72-bf8e104ebd20")
                        .displayName("Thanh Tran")
                        .cloudId("c1")
                        .build())
                .reporter(EsIntegrationUser.builder()
                        .id("928b49ef-1a08-4653-9a9f-bf48caf17372")
                        .displayName("srinath.chandrashekhar@levelops.io")
                        .cloudId("admin")
                        .build())
                .firstAssignee(EsIntegrationUser.builder()
                        .id("c7423dfe-b3ec-461e-9b72-bf8e104ebd20")
                        .displayName("Thanh Tran")
                        .cloudId("c1")
                        .build())
                .epic("_UNKNOWN_")
                .hops(1)
                .descSize(40)
                .bounces(0)
                .numAttachments(1)
                .originalEstimate(1.5f)
                .firstAttachmentAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .createdAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .updatedAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .resolvedAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .stateTransitionTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .dueAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .firstCommentAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .firstAssignedAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                .ingestedAt(new Timestamp(1647129600000L))
                .labels(List.of("regression", "testui"))
                .components(List.of("component1"))
                .priorityOrder(1)
                .storyPoints(4f)
                .resolution("_UNKNOWN_")
                .histStatuses(List.of(EsWorkItem.EsHistoricalStatus.builder()
                        .status("Done")
                        .statusId("2ba757ff-8e82-4558-bdaf-50b450312b3d")
                        .startTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .endTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .build()))
                .histAssignees(List.of(EsWorkItem.EsHistoricalAssignee.builder()
                        .assignee(EsIntegrationUser.builder()
                                .id("c7423dfe-b3ec-461e-9b72-bf8e104ebd20")
                                .displayName("Thanh Tran")
                                .cloudId("c1")
                                .build())
                        .startTime(Timestamp.from(Instant.parse("2021-09-28T16:07:30+00:00")))
                        .endTime(Timestamp.from(Instant.parse("2021-09-30T00:16:14+00:00"))).build()))
                .historicalStoryPoints(List.of(EsWorkItem.EsHistoricalStoryPoints.builder()
                        .storyPoints(7.0f)
                        .startTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .endTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .build()))
                .versions(List.of(EsWorkItem.EsVersion.builder()
                        .id(10007)
                        .name("Q4-2020")
                        .description("This is a sample release.")
                        .archived(false)
                        .released(false)
                        .overdue(false)
                        .startTime(Timestamp.from(Instant.parse("2022-03-08T06:48:58+00:00")))
                        .endTime(Timestamp.from(Instant.parse("2021-09-30T00:16:14+00:00")))
                        .build()))
                .fixVersions(List.of(EsWorkItem.EsVersion.builder()
                        .id(10006)
                        .name("Q3-2020")
                        .description("This is a sample release.")
                        .archived(false)
                        .released(false)
                        .overdue(false)
                        .startTime(Timestamp.from(Instant.parse("2022-03-08T06:48:58+00:00")))
                        .endTime(Timestamp.from(Instant.parse("2021-09-30T00:16:14+00:00")))
                        .build()))
                .historicalSprints(List.of(EsWorkItem.EsHistoricalSprint.builder()
                        .sprintId("3")
                        .name("Dec")
                        .state("CLOSED")
                        .goal("goal1")
                        .startTime(Timestamp.from(Instant.parse("2020-12-01T04:07:01+00:00")))
                        .endTime(Timestamp.from(Instant.parse("2021-01-06T04:07:00+00:00")))
                        .completedAt(Timestamp.from(Instant.parse("2021-01-12T16:18:23+00:00")))
                        .build()))
                .links(List.of(EsWorkItem.EsLink.builder()
                        .toWorkitemId("LEV-1926")
                        .relation("duplicates")
                        .build()))
                .sprintMappings(List.of(EsWorkItem.EsSprintMapping.builder()
                        .id("test11March\\Sprint 1")
                        .addedAt(1646996521L)
                        .planned(false)
                        .delivered(false)
                        .outsideOfSprint(false)
                        .ignorableIssueType(false)
                        .storyPointsPlanned(0.0f)
                        .storyPointsDelivered(0.0f)
                        .build()))
                .salesforceCases(List.of(EsWorkItem.EsSalesforceCase.builder()
                        .fieldKey("key_1")
                        .fieldValue("val_1")
                        .build()))
                .prioritiesSla(EsWorkItem.EsPrioritiesSla.builder()
                        .responseTime(86400L)
                        .solveTime(86400L)
                        .build())
                .milestones(List.of(EsWorkItem.EsMilestone.builder()
                        .id("eeeb7f30-cba6-4184-a462-d17d3e6d19f9")
                        .name("Milestone 1")
                        .parentName("LevelOps\\Effort Investment")
                        .fullName("LevelOps\\Effort Investment\\Milestone 1")
                        .state("current")
                        .startTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .endTime(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .completedAt(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                        .attributes(List.of(EsExtensibleField.builder()
                                        .name("teams")
                                        .arrValue(List.of("cgn-test/test11March/test11March Team"))
                                        .build(),
                                EsExtensibleField.builder()
                                        .name("project")
                                        .strValue("test11March")
                                        .build(),
                                EsExtensibleField.builder()
                                        .name("code_area")
                                        .strValue("test11March")
                                        .build(),
                                EsExtensibleField.builder()
                                        .name("organization")
                                        .strValue("test")
                                        .build(),
                                EsExtensibleField.builder()
                                        .name("acceptance_criteria")
                                        .strValue("accepted")
                                        .build()))
                        .build()))
                .customFields(List.of(EsExtensibleField.builder()
                                .name("customfield_10010")
                                .strValue("test")
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10011")
                                .intValue(1)
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10012")
                                .longValue(40L)
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10013")
                                .floatValue(1.5f)
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10014")
                                .boolValue(true)
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10015")
                                .dateValue(Timestamp.from(Instant.parse("2022-04-12T11:47:30.952Z")))
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10016")
                                .arrValue(List.of("test1", "test2"))
                                .build(),
                        EsExtensibleField.builder()
                                .name("customfield_10017")
                                .strValue("test1:test2")
                                .build()))
                .attributes(List.of(EsExtensibleField.builder()
                                .name("teams")
                                .arrValue(List.of("cgn-test/test11March/test11March Team"))
                                .build(),
                        EsExtensibleField.builder()
                                .name("project")
                                .strValue("test11March")
                                .build(),
                        EsExtensibleField.builder()
                                .name("code_area")
                                .strValue("test11March")
                                .build(),
                        EsExtensibleField.builder()
                                .name("organization")
                                .strValue("test")
                                .build(),
                        EsExtensibleField.builder()
                                .name("acceptance_criteria")
                                .strValue("accepted")
                                .build()))
                .build();
        Assertions.assertThat(actual).isEqualTo(expected);
    }
}
