import { ISSUE_MANAGEMENT_REPORTS } from "../applications/names";

export enum azureBAReportTypes {
  AZURE_ISSUES_PROGRESS_REPORT = ISSUE_MANAGEMENT_REPORTS.AZURE_ISSUES_PROGRESS_REPORT,
  AZURE_PROGRAM_PROGRESS_REPORT = ISSUE_MANAGEMENT_REPORTS.AZURE_PROGRAM_PROGRESS_REPORT
}
