package io.levelops.commons.databases.utils;

import com.google.common.collect.Lists;
import io.levelops.commons.jackson.DefaultObjectMapper;
import org.junit.Test;
import org.mockito.Mockito;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.times;

public class SqlInsertQueryTest {

    @Test
    public void testFull() throws SQLException {
        Map<String, List<String>> jsonObject = new HashMap<>();
        jsonObject.put("a", Lists.newArrayList("1", "2", "3"));
        jsonObject.put("b", Lists.newArrayList("4", "5", "6"));
        SqlInsertQuery query = SqlInsertQuery.builder(DefaultObjectMapper.get())
                .schema("company")
                .table("table")
                .field("string_field", "abc")
                .field("int_field", 123)
                .field("long_field", 123L)
                .field("float_field", 3.14f)
                .field("bool_field", true)
                .jsonField("json_field", jsonObject)
                .returnAutoGeneratedKeys(true)
                .build();

        assertThat(query.getSql()).isEqualTo("INSERT INTO company.table(string_field,int_field,long_field,float_field,bool_field,json_field) VALUES (?,?,?,?,?,to_json(?::json))");
        assertThat(query.getTableSql()).isEqualTo("company.table");
        assertThat(query.getFieldsSql()).isEqualTo("string_field,int_field,long_field,float_field,bool_field,json_field");
        assertThat(query.getValuesSql()).isEqualTo("?,?,?,?,?,to_json(?::json)");
        assertThat(query.getReturnAutoGeneratedKeys()).isTrue();

        PreparedStatement mock = Mockito.mock(PreparedStatement.class);
        query.setValues(mock);

        Mockito.verify(mock, times(1)).setObject(eq(1), eq("abc"));
        Mockito.verify(mock, times(1)).setObject(eq(2), eq(123));
        Mockito.verify(mock, times(1)).setObject(eq(3), eq(123L));
        Mockito.verify(mock, times(1)).setObject(eq(4), eq(3.14f));
        Mockito.verify(mock, times(1)).setObject(eq(5), eq(true));
        Mockito.verify(mock, times(1)).setObject(eq(6), eq("{\"a\":[\"1\",\"2\",\"3\"],\"b\":[\"4\",\"5\",\"6\"]}"));
    }


    @Test
    public void testTable() throws SQLException {
        SqlInsertQuery query = SqlInsertQuery.builder(DefaultObjectMapper.get())
                .table("table")
                .build();
        assertThat(query.getTableSql()).isEqualTo("table");

        SqlInsertQuery query2 = SqlInsertQuery.builder(DefaultObjectMapper.get())
                .table("table")
                .schema("company")
                .build();
        assertThat(query2.getTableSql()).isEqualTo("company.table");
    }

    @Test
    public void testReturning() throws SQLException {
        SqlInsertQuery query = SqlInsertQuery.builder(DefaultObjectMapper.get())
                .build();
        assertThat(query.getReturnAutoGeneratedKeys()).isFalse();

        SqlInsertQuery query2 = SqlInsertQuery.builder(DefaultObjectMapper.get())
                .returnAutoGeneratedKeys(true)
                .build();
        assertThat(query2.getReturnAutoGeneratedKeys()).isTrue();
    }
}