package io.levelops.commons.databases.utils;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public interface SqlQuery {

    String getSql();

    PreparedStatement setValues(PreparedStatement statement) throws SQLException;

    boolean getReturnAutoGeneratedKeys();

    default PreparedStatement prepareStatement(Connection connection) throws SQLException {
        PreparedStatement preparedStatement;
        if (getReturnAutoGeneratedKeys()) {
            preparedStatement = connection.prepareStatement(this.getSql(), Statement.RETURN_GENERATED_KEYS);
        } else {
            preparedStatement = connection.prepareStatement(this.getSql());
        }
        return setValues(preparedStatement);
    }

}
