export enum USERROLES {
  ADMIN = "admin",
  LIMITED_USER = "limited_user",
  AUDITOR = "auditor",
  RESTRICTED_USER = "restricted_user",
  ASSIGNED_ISSUES_USER = "assigned_issues_user",
  PUBLIC_DASHBOARD = "public_dashboard",
  SUPER_ADMIN = "super_admin", // may be change later
  ORG_UNIT_ADMIN = "org_admin_user"
}

export enum USERROLESUPPER {
  ADMIN = "ADMIN",
  LIMITED_USER = "LIMITED_USER",
  AUDITOR = "AUDITOR",
  RESTRICTED_USER = "RESTRICTED_USER",
  ASSIGNED_ISSUES_USER = "ASSIGNED_ISSUES_USER",
  PUBLIC_DASHBOARD = "PUBLIC_DASHBOARD",
  SUPER_ADMIN = "SUPER_ADMIN", // may be change later
  ORG_UNIT_ADMIN = "ORG_ADMIN_USER"
}

export enum USERLANDINGPAGE {
  DASHBOARD = "DASHBOARD",
  ISSUES = "ISSUES",
  REPORTS = "REPORTS",
  EMPTY = "EMPTY"
}

export const USER_ADMIN_ROLES = [USERROLES.ADMIN, USERROLES.SUPER_ADMIN];
export const CONFIGURATION_ADMIN_ROLES = [USERROLES.ADMIN, USERROLES.SUPER_ADMIN, USERROLES.ORG_UNIT_ADMIN];
export const USER_NON_ADMIN_ROLES = [
  USERROLES.ASSIGNED_ISSUES_USER,
  USERROLES.AUDITOR,
  USERROLES.LIMITED_USER,
  USERROLES.RESTRICTED_USER,
  USERROLES.PUBLIC_DASHBOARD,
  USERROLES.ORG_UNIT_ADMIN
];
export const ISSUE_ROUTES_RBAC = [
  USERROLES.ADMIN,
  USERROLES.LIMITED_USER,
  USERROLES.ASSIGNED_ISSUES_USER,
  USERROLES.SUPER_ADMIN
];
export const DASHBOARD_ID_IN_HEADERS_ROLES = [
  USERROLES.ASSIGNED_ISSUES_USER,
  USERROLES.AUDITOR,
  USERROLES.LIMITED_USER,
  USERROLES.RESTRICTED_USER
];

export const WIDGET_EXTRAS_ROLES = [...USER_ADMIN_ROLES, USERROLES.PUBLIC_DASHBOARD, USERROLES.ORG_UNIT_ADMIN];
