// external integration types
export const INTEGRATION_TYPE = "INTEGRATION_TYPE";
export const INTEGRATION_SUB_TYPE = "INTEGRATION_SUB_TYPE";
export const ACTIVE_INTEGRATION_STEP = "ACTIVE_INTEGRATION_STEP";
export const INTEGRATION_COMPLETE = "INTEGRATION_COMPLETE";
export const INTEGRATION_NAME = "INTEGRATION_NAME";
export const INTEGRATION_STATE = "INTEGRATION_STATE";
export const INTEGRATION_CODE = "INTEGRATION_CODE";
export const INTEGRATION_FORM = "INTEGRATION_FORM";
export const INTEGRATION_ID = "INTEGRATION_ID";

// error action types
export const ADD_ERROR = "ADD_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

// drag and drop action types

export const ADD_DASHBOARD_DRAG = "DASHBOARD_DRAG";
export const ADD_DASHBOARD_DROP = "DASHBOARD_DROP";
export const CLEAR_DASHBOARD_DRAG = "CLEAR_DASHBOARD_DRAG";
export const CLEAR_DASHBOARD_DROP = "CLEAR_DASHBOARD_DROP";

// session action types

export const SESSION_LOGIN = "SESSION_LOGIN";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_PROFILE = "SESSION_PROFILE";
export const SESSION_CURRENT_USER = "SESSION_CURRENT_USER";
export const CURRENT_USER_ENTITLEMENTS = "CURRENT_USER_ENTITLEMENTS";

export const SESSION_LOAD = "SESSION_LOAD";
export const SESSION_ERROR = "SESSION_ERROR";
export const CLEAR_SESSION_ERROR = "CLEAR_SESSION_ERROR";
export const SESSION_REFRESH = "SESSION_REFRESH";
export const SESSION_SSO_LOGIN = "SESSION_SSO_LOGIN";
export const SESSION_MFA = "SESSION_MFA";
export const SESSION_MFA_CLEAR = "SESSION_MFA_CLEAR";
export const SESSION_MFA_GET = "SESSION_MFA_GET";
export const SESSION_MFA_ENROLL = "SESSION_MFA_ENROLL";
export const SESSION_MFA_ENROLL_GET = "SESSION_MFA_ENROLL_GET";
export const SESSION_MFA_ENROLL_POST = "SESSION_MFA_ENROLL_POST";
export const SESSION_MFA_ENROLL_CLEAR = "SESSION_MFA_ENROLL_CLEAR";
export const SESSION_GET_ME = "SESSION_GET_ME";

// pagination action types
export const PAGINATION_FILTERS = "PAGINATION_FILTERS";
export const PAGINATION_GET = "PAGINATION_GET";
export const PAGINATION_SET = "PAGINATION_SET";
export const PAGINATION_DATA = "PAGINATION_DATA";
export const PAGINATION_LOADING = "PAGINATION_LOADING";
export const PAGINATION_DONE_LOADING = "PAGINATION_DONE_LOADING";
export const PAGINATION_ERROR = "PAGINATION_ERROR";
export const PAGINATION_CLEAR = "PAGINATION_CLEAR";

// rest api action types

export const RESTAPI_LOADING = "RESTAPI_LOADING";
export const RESTAPI_ERROR = "RESTAPI_ERROR";
export const RESTAPI_DATA = "RESTAPI_DATA";
export const SET_SELECTED_ENTITY = "SET_SELECTED_ENTITY";
export const DEMO_WIGET_UPDATE = "DEMO_WIGET_UPDATE";
export const SET_SELECTED_CHILD_ID = "SET_SELECTED_CHILD_ID";
export const SET_ENTITY = "SET_ENTITY";
export const SET_ENTITIES = "SET_ENTITIES";
export const DELETE_ENTITIES = "DELETE_ENTITIES";
export const MAKE_WIDGETS_REVERSIBLE = "MAKE_WIDGETS_REVERSIBLE";
export const REVERT_WIDGET_CHANGES = "REVERT_WIDGET_CHANGES";
export const CLEAR_WIDGET_HISTORY = "CLEAR_WIDGET_HISTORY";
export const RESTAPI_CLEAR = "RESTAPI_CLEAR";
export const RESTAPI_CLEAR_ALL = "RESTAPI_CLEAR_ALL";
export const RESTAPI_ERROR_CODE = "RESTAPI_ERROR_CODE";

// widgets

export const WIDGET_GET = "WIDGET_GET";
export const WIDGET_DATA = "WIDGET_DATA";
export const WIDGET_CLEAR = "WIDGET_CLEAR";

// tags

export const TAGS_GET_OR_CREATE = "TAGS_GET_OR_CREATE";

// KBs
export const KBS_GET_OR_CREATE = "KBS_GET_OR_CREATE";

// users

export const USERS_GET_OR_CREATE = "USERS_GET_OR_CREATE";
export const USER_TRELLIS_PERMISSION_UPDATE = "USER_TRELLIS_PERMISSION_UPDATE";

// questionnaires
export const Q_EXPORT = "Q_EXPORT";
export const Q_IMPORT = "Q_IMPORT";

// files

export const FILES_GET = "FILES_GET";

// reset password request

export const RESET_PASSWORD = "RESET_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

// tab counts action

export const WORKBENCH_TAB_COUNTS = "WORKBENCH_TAB_COUNTS";
export const WORKBENCH_TAB_LOADING = "WORKBENCH_TAB_LOADING";
export const WORKBENCH_TAB_ERROR = "WORKBENCH_TAB_ERROR";
export const WORKBENCH_TAB_DATA = "WORKBENCH_TAB_DATA";
export const WORKBENCH_TAB_CLEAR = "WORKBENCH_TAB_CLEAR";

// ui-actions
export const uiActions = {
  TOGGLE_FULLSCREEN_MODAL: "@@core/ui/TOGGLE_FULLSCREEN_MODAL"
};

// new integrations
export const integrationsActions = {
  SET_INTEGRATION_TYPE: "@@integrations/ui/SET_INTEGRATION_TYPE",
  SET_INTEGRATION_SUB_TYPE: "@@integrations/ui/SET_INTEGRATION_SUB_TYPE",
  SET_INTEGRATION_CREDENTIALS: "@@integrations/ui/SET_INTEGRATION_CREDENTIALS",
  SET_INTEGRATION_INFORMATION: "@@integrations/ui/SET_INTEGRATION_INFORMATION",
  SET_INTEGRATION_TEAMS: "@@integrations/ui/SET_INTEGRATION_TEAMS",
  SET_INTEGRATION_PRODUCTS: "@@integrations/ui/SET_INTEGRATION_PRODUCTS",
  SET_INTEGRATION_STATE: "@@integrations/ui/SET_INTEGRATION_STATE",
  SET_INTEGRATION_STEP: "@@integrations/ui/SET_INTEGRATION_STEP",
  RESET_CREATE_STORE: "@@integrations/ui/RESET_CREATE_STORE",
  GET_INTEGRATIONS_LIST: "GET_INTEGRATIONS_LIST",
  INTEGRATIONS_LIST_LOADED: "INTEGRATIONS_LIST_LOADED"
};

export const trellisProfileActions = {
  TRELLIS_PROFILE_CREATE: "@@trellisProfile/CREATE",
  TRELLIS_PROFILE_UPDATE: "@@trellisProfile/UPDATE",
  TRELLIS_PROFILE_PARTIAL_UPDATE: "@@trellisProfile/PARTIAL_UPDATE",
  TRELLIS_PROFILE_SAVE_SUCCESSFUL: "@@trellisProfile/SAVE_SUCCESS",
  TRELLIS_PROFILE_SAVE_FAILED: "@@trellisProfile/SAVE_FAILED",

  TRELLIS_PROFILE_READ: "@@trellisProfile/READ",
  TRELLIS_PROFILE_LOAD_SUCCESSFUL: "@@trellisProfile/LOAD_SUCCESS",
  TRELLIS_PROFILE_CLEAR: "@@trellisProfile/CLEAR",
  TRELLIS_PROFILE_LOAD_FAILED: "@@trellisProfile/FAILED",

  GET_TRELLIS_PROFILES_LIST: "@@trellisProfile/GET_LIST",
  TRELLIS_PROFILES_LIST_LOAD_SUCCESSFUL: "@@trellisProfile/LIST_LOAD_SUCCESS",
  TRELLIS_PROFILES_LIST_LOAD_FAILED: "@@trellisProfile/LIST_LOAD_FAILED",
  REUSE_EXISTING_TRELLIS_PROFILE_LIST: "@@trellisProfile/REUSE_EXISITNG",
  SET_NO_INTEGRATIONS: "@@trellisProfile/NO_INTEGRATIONS",

  TRELLIS_PROFILE_CLONE: "@@trellisProfile/CLONE",
  TRELLIS_PROFILE_DELETE: "@@trellisProfile/DELETE",

  SAVE_WORKSPACE_OU_LIST: "@@trellisProfile/SAVE_WORKSPACE_OU_LIST",
  GET_WORKSPACE_OU_LIST: "@@trellisProfile/GET_WORKSPACE_OU_LIST",

  ASSOCIATE_OU_TO_PROFILE: "@@trellisProfile/ASSOCIATE_OU_TO_PROFILE"
};

export const widgetAPIActions = {
  GET_DATA: "@@widget/GET_DATA",
  GET_DATA_FAILED: "@wwidget/GET_DATA_FAILED",
  GET_DATA_SUCCESS: "@wwidget/GET_DATA_SUCCESS"
};

export const devRawStatGraphAPIActions = {
  GET_GRAPH_DATA: "@@widget/GET_GRAPH_DATA",
  GET_GRAPH_DATA_FAILED: "@@widget/GET_GRAPH_DATA_FAILED",
  GET_GRAPH_DATA_SUCCESS: "@@widget/GET_GRAPH_DATA_SUCCESS"
};
// workitem flow

export const WORKITEM_FLOW = "WORKITEM_FLOW";
export const workflowProfileActions = {
  WORKFLOW_PROFILE_CREATE: "@@workflowProfile/CREATE",
  WORKFLOW_PROFILE_UPDATE: "@@workflowProfile/UPDATE",
  WORKFLOW_PROFILE_SAVE_SUCCESSFUL: "@@workflowProfile/SAVE_SUCCESS",
  WORKFLOW_PROFILE_SAVE_FAILED: "@@workflowProfile/SAVE_FAILED",

  WORKFLOW_PROFILE_READ: "@@workflowProfile/READ",
  WORKFLOW_PROFILE_LIST_LOAD_SUCCESSFUL: "@@workflowProfile/LOAD_SUCCESS",
  WORKFLOW_PROFILES_LIST_LOAD_FAILED: "@@workflowProfile/LIST_LOAD_FAILED",
  WORKFLOW_PROFILE_CLEAR: "@@workflowProfile/CLEAR",
  WORKFLOW_PROFILE_FILTERS: "@@workflowProfile/FILTERS",
  ASSOCIATE_OU_TO_PROFILE: "@@workflowProfile/ASSOCIATE_OU_TO_PROFILE"
};

export const workflowProfileByOuActions = {
  WORKFLOW_PROFILE_READ_BY_OU: "@@workflowProfileByOu/READ",
  WORKFLOW_PROFILE_READ_BY_OU_SUCCESSFUL: "@@workflowProfileByOu/LOAD_SUCCESS",
  WORKFLOW_PROFILE_READ_BY_OU_FAILED: "@@workflowProfileByOu/LOAD_FAILED",
  REUSE_EXISTING_WORKFLOW_PROFILE_BY_OU: "@@workflowProfileByOu/REUSE_EXISITNG",
  WORKFLOW_PROFILE_READ_BY_OU_CLEAR: "@@workflowProfileByOu/CLEAR"
};

// common restapi action

export const RESTAPI_CALL = "RESTAPI_CALL";
export const RESTAPI_READ = "RESTAPI_READ";
export const RESTAPI_WRITE = "RESTAPI_WRITE";

export const JIRA_FILTER_VALUES = "JIRA_FILTER_VALUES";
export const JIRA_FILTER_VALUES_PRE_FETCHED = "JIRA_FILTER_VALUES_PRE_FETCHED";
export const JIRA_ZENDESK_FILTER_VALUES = "JIRA_ZENDESK_FILTER_VALUES";
export const JIRA_SALESFORCE_FILTER_VALUES = "JIRA_SALESFORCE_FILTER_VALUES";
export const LEAD_TIME_FILTER_VALUES = "LEAD_TIME_FILTER_VALUES";
export const AZURE_FILTER_VALUES = "AZURE_FILTER_VALUES";
export const TESTRAILS_FILTER_VALUES = "TESTRAILS_FILTER_VALUES";

export const GENERIC_FILTER_VALUES = "GENERIC_FILTER_VALUES";

export const CSV_DOWLOAD_DRILLDOWN = "CSV_DOWNLOAD_DRILLDOWN";
export const CSV_DOWLOAD_TRIAGE_GRID_VIEW = "CSV_DOWNLOAD_TRIAGE_GRID_VIEW";
export const CSV_DOWLOAD_USER = "CSV_DOWNLOAD_USER";
export const CSV_DOWLOAD_SAMPLE_USER = "CSV_DOWNLOAD_SAMPLE_USER";

export const JIRA_ZENDESK = "JIRA_ZENDESK";
export const JIRA_SALESFORCE = "JIRA_SALESFORCE";

export const TRIAGE_MATCHING_JOGS = "TRIAGE_MATCHING_JOGS";
export const FETCH_JOB_RESULTS = "FETCH_JOB_RESULTS";

// Assessment Templates
export const ASSESSMENT_TEMPLATE_POST = "ASSESSMENT_TEMPLATE_POST";
export const ASSESSMENT_TEMPLATE_GET = "ASSESSMENT_TEMPLATE_GET";

//Levelops Widgets
export const LEVELOPS_WIDGETS = "LEVELOPS_WIDGETS";

//Generic IDS Map
export const GENERIC_IDS_MAP = "GENERIC_IDS_MAP";
export const GENERIC_STORED_IDS_MAP = "GENERIC_STORED_IDS_MAP";

export const JIRA_ZENDESK_SALESFORCE_STAGES_WIDGETS = "JIRA_ZENDESK_SALESFORCE_STAGES_WIDGETS";

export const JIRA_ZENDESK_SALESFORCE_C2F_WIDGETS = "JIRA_ZENDESK_SALESFORCE_C2F_WIDGETS";

export const LOAD_DASHBOARD = "LOAD_DASHBOARD";

export const DASHBOARD_SET = "DASHBOARD_SET";
export const MULTI_REPORT_WIDGET_REPORT_ADD = "MULTI_REPORT_WIDGET_REPORT_ADD";
export const MULTI_REPORT_WIDGET_REPORT_DELETE = "MULTI_REPORT_WIDGET_REPORT_DELETE";
export const MULTI_REPORT_WIDGET_REPORT_NAME_UPDATE = "MULTI_REPORT_WIDGET_REPORT_NAME_UPDATE";
export const DASHBOARD_WIDGET_ADD = "DASHBOARD_WIDGET_ADD";
export const WIDGET_REPORTS_LIST = "WIDGET_REPORTS_LIST";
export const SET_REPORTS = "SET_REPORTS";
export const DASHBOARD_WIDGET_REMOVE = "DASHBOARD_WIDGET_REMOVE";
export const DASHBOARD_WIDGET_RESET = "DASHBOARD_WIDGET_RESET";
export const DASHBOARD_WIDGET_SET_ORDER = "DASHBOARD_WIDGET_SET_ORDER";
export const DASHBOARD_WIDGET_REORDER = "DASHBOARD_WIDGET_REORDER";
export const DASHBOARD_WIDGET_UPDATE = "DASHBOARD_WIDGET_UPDATE";
export const DASHBOARD_REMOTE_WIDGET_UPDATE = "DASHBOARD_REMOTE_WIDGET_UPDATE";
export const DASHBOARD_WIDGET_BULK_UPDATE = "DASHBOARD_WIDGET_BULK_UPDATE";
export const DASHBOARD_WIDGET_CLONE = "DASHBOARD_WIDGET_CLONE";
export const DASHBOARD_UPDATE = "DASHBOARD_UPDATE";
export const LOAD_DASHBOARD_INTEGRATIONS = "LOAD_DASHBOARD_INTEGRATIONS";
export const DASHBOARD_TIME_UPDATE = "DASHBOARD_TIME_UPDATE";
export const CLEAR_STORE = "CLEAR_STORE";
export const DASHBOARD_TIME_RANGE_TOGGLE = "DASHBOARD_TIME_RANGE_TOGGLE";
export const WIDGET_DRILLDOWN_COLUMNS_UPDATE = "WIDGET_DRILLDOWN_COLUMNS_UPDATE";
export const UPDATE_DASHBOARD_WIDGETS = "UPDATE_DASHBOARD_WIDGETS";
export const WIDGET_SELECTED_COLUMNS_UPDATE = "WIDGET_SELECTED_COLUMNS_UPDATE";
export const WIDGET_TABLE_FILTERS_UPDATE = "WIDGET_TABLE_FILTERS_UPDATE";
export const WIDGET_METADATA_FIELD_UPDATE = "WIDGET_METADATA_FIELD_UPDATE";

export const GENERIC_TABLE_CSV_DOWNLOAD = "GENERIC_TABLE_CSV_DOWNLOAD";
export const SUPPORTED_FILTER_GET = "SUPPORTED_FILTER_GET";

export const DASHBOARD_DEFAULT = "DASHBOARD_DEFAULT";
export const ZENDESK_FILTER_VALUES = "ZENDESK_FILTER_VALUES";

// BA widgets actions
export const JIRA_PROGRESS_STAT = "JIRA_PROGRESS_STAT";
export const JIRA_PROGRESS_REPORT = "JIRA_PROGRESS_REPORT";
export const JIRA_EPIC_PRIORITY_REPORT = "JIRA_EPIC_PRIORITY_REPORT";
export const JIRA_BURN_DOWN_REPORT = "JIRA_BURN_DOWN_REPORT";
export const JIRA_EFFORT_INVESTMENT_STAT = "JIRA_EFFORT_INVESTMENT_STAT";
export const JIRA_EFFORT_INVESTMENT_TREND_REPORT = "JIRA_EFFORT_INVESTMENT_TREND_REPORT";
export const JIRA_EI_COMPLETED_ENGINEER_REPORT = "JIRA_EI_COMPLETED_ENGINEER_REPORT";
export const JIRA_EI_ALIGNMENT_REPORT = "JIRA_EI_ALIGNMENT_REPORT";
export const JIRA_EI_ACTIVE_ENGINEER_REPORT = "JIRA_EI_ACTIVE_ENGINEER_REPORT";
export const EFFORT_INVESTMENT_TEAM_REPORT = "EFFORT_INVESTMENT_TEAM_REPORT";
export const EFFORT_INVESTMENT_SINGLE_STAT = "EFFORT_INVESTMENT_SINGLE_STAT";
export const AZURE_PROGRESS_REPORT = "AZURE_PROGRESS_REPORT";
export const AZURE_PROGRAM_PROGRESS_REPORT = "AZURE_PROGRAM_PROGRESS_REPORT";

export const GENERIC_REST_API_SET = "GENERIC_REST_API_SET";

//ticket categorization schemes
export const TICKET_CATEGORIZATION_SCHEME_DELETE = "TICKET_CATEGORIZATION_SCHEME_DELETE";
export const TICKET_CATEGORIZATION_SCHEME_CLONE_LIST = "TICKET_CATEGORIZATION_SCHEME_CLONE_LIST";
export const TICKET_CATEGORIZATION_SCHEME_CLONE_GET = "TICKET_CATEGORIZATION_SCHEME_CLONE_GET";
export const TICKET_CATEGORIZATION_SCHEME_SET_TO_DEFAULT = "TICKET_CATEGORIZATION_SCHEME_SET_TO_DEFAULT";
export const TICKET_CATEGORIZATION_SCHEME_RESET_COLOR_PALETTE = "TICKET_CATEGORIZATION_SCHEME_RESET_COLOR_PALETTE";
export const TICKET_CATEGORIZATION_FILTERS = "TICKET_CATEGORIZATION_FILTERS";
export const TICKET_CATEGORIZATION_CREATE_UPDATE = "TICKET_CATEGORIZATION_CREATE_UPDATE";

// Organization Unit
export const SET_OU_DEFAULT_DASHBOARD = "SET_OU_DEFAULT_DASHBOARD";
export const ORGANIZATION_UNIT_DELETE = "ORGANIZATION_UNIT_DELETE";
export const ORGANIZATION_UNIT_CLONE = "ORGANIZATION_UNIT_CLONE";
export const ORGANZATION_UNIT_DASHBOARDS = "ORGANZATION_UNIT_DASHBOARDS";
export const ORGANIZATION_UNIT_SAVE = "ORGANIZATION_UNIT_SAVE";
export const ORGANIZATION_UNIT_UPDATE = "ORGANIZATION_UNIT_UPDATE";
export const ORGANIZATION_UNIT_GET = "ORGANIZATION_UNIT_GET";
export const ORGANIZATION_UNIT_FILTER_VALUES = "ORGANIZATION_UNIT_FILTER_VALUES";
export const ORGANIZATION_UNIT_UTILITY_SAGA = "ORGANIZATION_UNIT_UTILITY_SAGA";
export const ORGANIZATION_CUSTOM_FIELDS_SAGA = "ORGANIZATION_CUSTOM_FIELDS_SAGA";
export const GET_ALL_ORG_UNTIS = "GET_ALL_ORG_UNTIS";
// jenkins actions
export const JENKINS_INTEGRATION_LIST = "JENKINS_INTEGRATION_LIST";

// sprint reports
export const JIRA_SPRINT_REPORTS_LIST = "JIRA_SPRINT_REPORTS_LIST";
export const JIRA_SPRINT_FILTER_LIST = "JIRA_SPRINT_FILTERS_LIST";

// Velocity Configs
export const VELOCITY_CONFIG_GET = "VELOCITY_CONFIG_GET";
export const VELOCITY_CONFIG_CLONE = "VELOCITY_CONFIG_CLONE";
export const WORKFLOW_PROFILE_CLONE = "WORKFLOW_PROFILE_CLONE";
export const VELOCITY_CONFIG_DELETE = "VELOCITY_CONFIG_DELETE";
export const VELOCITY_CONFIG_SET_TO_DEFAULT = "VELOCITY_CONFIG_SET_TO_DEFAULT";

// Assignee Time Report
export const ASSIGNEE_TIME_REPORT_FETCH = "ASSIGNEE_TIME_REPORT_FETCH";

// widget library actions
export const WIDGET_LIBRARY_FILTER_UPDATED = "WIDGET_LIBRARY_LIST_UPDATE";
export const WIDGET_LIBRARY_SEARCH_QUERY_UPDATED = "WIDGET_LIBRARY_SEARCH_QUERY_UPDATED";
export const WIDGET_LIBRARY_CATEGORY_UPDATED = "WIDGET_LIBRARY_CATEGORY_UPDATED";
export const WIDGET_LIBRARY_CATEGORY_SORT = "WIDGET_LIBRARY_CATEGORY_SORT";
export const RESET_WIDGET_LIBRARY = "RESET_WIDGET_LIBRARY";
export const RESET_WIDGET_LIBRARY_FILTERS = "RESET_WIDGET_LIBRARY_FILTERS";
export const WIDGET_LIBRARY_LIST_UPDATED = "WIDGET_LIBRARY_LIST_UPDATED";

export const TABLE_LIBRARY_REPORT_LIST = "TABLE_LIBRARY_REPORT_LIST";
export const REST_REPORT_LIST = "REST_REPORT_LIST";
export const CATEGORIES_FILTERS_VALUES = "CATEGORIES_FILTERS_VALUES";
export const AZURE_CATEGORIES_FILTER_VALUES = "AZURE_CATEGORIES_FILTER_VALUES";
export const CATEGORIES_FILTERS_VALUES_WITH_STATUS = "CATEGORIES_FILTERS_VALUES_WITH_STATUS";
export const AZURE_CATEGORIES_FILTER_VALUES_WITH_STATUS = "AZURE_CATEGORIES_FILTER_VALUES_WITH_STATUS";
export const SET_CATEGORIES_VALUES_DATA = "SET_CATEGORIES_VALUES_DATA";

//Ingestion Integration
export const INGESTION_INTEGRATION = "INGESTION_INTEGRATION";

// Integration Monitoring
export const INTEGRATION_MONITORING_ACTION = "INTEGRATION_MONITORING_ACTION";

export const COPY_WIDGET_TO_DASHBOARD = "COPY_WIDGET_TO_DASHBOARD";

export const ISSUE_LEAD_TIME_FILTER_VALUES = "ISSUE_LEAD_TIME_FILTER_VALUES";

export const SLA_FILTERS_DATA = "SLA_FILTERS_DATA";

export const JIRA_INTEGRATION_CUSTOM_FIELDS = "JIRA_INTEGRATION_CUSTOM_FIELDS";

export const AZURE_INTEGRATION_CUSTOM_FIELDS = "AZURE_INTEGRATION_CUSTOM_FIELDS";

export const CODE_VOL_VS_DEPLOYMENT_VALUES = "CODE_VOL_VS_DEPLOYMENT_VALUES";

export const REST_API_SELECT_GENERIC_LIST = "REST_API_SELECT_GENERIC_LIST";
export const SET_REQUIRED_FIELD_ERROR = "SET_REQUIRED_FIELD_ERROR";

export const TESTRAILS_INTEGRATION_CUSTOM_FIELDS = "TESTRAILS_INTEGRATION_CUSTOM_FIELDS";

/**
 * Report CSV download action
 */
export const REPORT_CSV_DOWNLOAD = "REPORT_CSV_DOWNLOAD";
export const ZENDESK_INTEGRATION_CUSTOM_FIELDS = "ZENDESK_INTEGRATION_CUSTOM_FIELDS";
export const OU_SCORE_OVERVIEW = "OU_SCORE_OVERVIEW";

export const DEV_PRODUCTIVITY_FEATURE_DRILLDOWN_GET = "DEV_PRODUCTIVITY_FEATURE_DRILLDOWN_GET";
export const DEV_PRODUCTIVITY_SCORE_REPORT_LIST = "DEV_PRODUCTIVITY_SCORE_REPORT_LIST";
export const DEV_PRODUCTIVITY_CSV_DOWNLOAD = "DEV_PRODUCTIVITY_CSV_DOWNLOAD";
export const DEV_PRODUCTIVITY_PR_ACTIVITY = "DEV_PRODUCTIVITY_PR_ACTIVITY";
export const RAW_STATS_CSV_DOWNLOAD = "RAW_STATS_CSV_DOWNLOAD";

export const GET_API_FILTER_DATA = "GET_API_FILTER_DATA";

export const GENERIC_REST_API_LOADING = "GENERIC_REST_API_LOADING";
export const GENERIC_REST_API_ERROR = "GENERIC_REST_API_ERROR";

export const LOAD_DASHBOARD_INTEGRATIONS_CONFIG = "LOAD_DASHBOARD_INTEGRATIONS_CONFIG";

export const LOAD_DASHBOARD_FIELDS_LIST = "LOAD_DASHBOARD_FIELDS_LIST";

export const FILTER_WIDGETS_CUSTOM_FIELDS = "FILTER_WIDGETS_CUSTOM_FIELDS";

export const CLEAR_ORG_UNITS_LIST_FOR_INTEGRATION = "CLEAR_ORG_UNITS_LIST_FOR_INTEGRATION";
export const TENANT_STATE = "TENANT_STATE";

export const CACHED_GENERIC_REST_API_SET = "CACHED_GENERIC_REST_API_SET";
export const CACHED_GENERIC_REST_API_LOADING = "CACHED_GENERIC_REST_API_LOADING";
export const CACHED_GENERIC_REST_API_ERROR = "CACHED_GENERIC_REST_API_ERROR";
export const CACHED_GENERIC_REST_API_CLEAR = "CACHED_GENERIC_REST_API_CLEAR";
export const CACHED_GENERIC_REST_API_INVALIDATE = "CACHED_GENERIC_REST_API_INVALIDATE";
export const CACHED_GENERIC_REST_API_READ = "CACHED_GENERIC_REST_API_READ";
export const CACHED_GENERIC_REST_API_APPEND = "CACHED_GENERIC_REST_API_APPEND";
export const SELF_ONBOARDING_INTEGRATION_CREATE = "SELF_ONBOARDING_INTEGRATION_CREATE";
export const SELF_ONBOARDING_INTEGRATION_YAML_DOWNLOAD = "SELF_ONBOARDING_INTEGRATION_YAML_DOWNLOAD";
export const LEAD_TIME_BY_TIME_SPENT_IN_STAGES = "LEAD_TIME_BY_TIME_SPENT_IN_STAGES";

export const DEMO_DASHBOARD_UPDATE = "DEMO_DASHBOARD_UPDATE";
export const JIRA_RELEASE_TABLE_CSV_REPORT = "JIRA_RELEASE_TABLE_CSV_REPORT";

// workspace actions

export const SET_WORKSPACE_STATE = "SET_WORKSPACE_STATE";
export const SET_SELECTED_WORKSPACE = "SET_SELECTED_WORKSPACE";
export const SET_OU_HEADER_SELECTED_WORKSPACE = "SET_OU_HEADER_SELECTED_WORKSPACE";
export const WORKSPACE_READ = "WORKSPACE_READ";
export const WORK_SPACE_API_CLEAR = "WORK_SPACE_API_CLEAR";
export const SET_SESSION_SELECTED_WORKSPACE = "SET_SESSION_SELECTED_WORKSPACE";
export const GET_WORKSPACE_CATEGORIES = "GET_WORKSPACE_CATEGORIES";
export const GET_OU_OPTIONS = "GET_OU_OPTIONS";
export const CLEAR_SELECTED_WORKSPACE = "CLEAR_SELECTED_WORKSPACE";

export const GET_OU_FILTERS_TO_DISPLAY = "GET_OU_FILTERS_TO_DISPLAY";

// cached integration actions

export const SET_CACHED_INTEGRATION_DATA_STATE = "SET_CACHED_INTEGRATION_DATA_STATE";
export const APPEND_CACHED_INTEGRATION_DATA_STATE = "APPEND_CACHED_INTEGRATION_DATA_STATE";
export const SET_CACHED_INTEGRATION_LOADING_STATE = "SET_CACHED_INTEGRATION_LOADING_STATE";
export const SET_CACHED_INTEGRATION_ERROR_STATE = "SET_CACHED_INTEGRATION_ERROR_STATE";
export const CACHED_INTEGRATION_READ = "CACHED_INTEGRATION_READ";
export const CLEAR_CACHED_INTEGRATION = "CLEAR_CACHED_INTEGRATION";
export const CACHED_INTEGRATION_INVALIDATE = "CACHED_INTEGRATION_INVALIDATE";
export const UPDATE_SELECTED_DASHBOARD_DATA = "UPDATE_SELECTED_DASHBOARD_DATA";
export const SET_INTEGRAIONS = "SET_INTEGRAIONS";
export const INVALIDATE_HAS_ALL_INT = "INVALIDATE_HAS_ALL_INT";

//Dora
export const DORA_LEAD_TIME_GET_DATA = "DORA_LEAD_TIME_GET_DATA";
export const DORA_LEAD_TIME_FOR_CHANGE_GET_DATA = "DORA_LEAD_TIME_FOR_CHANGE_GET_DATA";
export const DORA_MEAN_TIME_TO_RESTORE_GET_DATA = "DORA_MEAN_TIME_TO_RESTORE_GET_DATA";

export const cicdJobParamsActions = {
  GET_CICD_JOB_PARAMS: "@@cicdJobParamsActions/GET_CICD_JOB_PARAMS",
  GET_CICD_JOB_PARAMS_SUCCESS: "@@cicdJobParamsActions/GET_CICD_JOB_PARAMS_SUCCESS",
  GET_CICD_JOB_PARAMS_FAIL: "@@cicdJobParamsActions/GET_CICD_JOB_PARAMS_FAIL",
  CLEAR_CICD_JOB_PARAMS: "@@cicdJobParamsActions/CLEAR_CICD_JOB_PARAMS"
};

//Table Report
export const TABLE_REPORT_GET_DATA = "TABLE_REPORT_GET_DATA";

//Modal
export const UNSAVED_MODAL_CHANGES = "UNSAVED_MODAL_CHANGES";

//SEI on Harness
export const FETCH_WORKSPACE_FOR_HARNESS = "FETCH_WORKSPACE_FOR_HARNESS";

// new trellis actions
export const GET_DEV_PROD_PROFILE_LIST = "GET_DEV_PROD_PROFILE_LIST";
export const PUT_DEV_PROD_PROFILE = "PUT_DEV_PROD_PROFILE";
export const GET_DEV_PROD_CENTRAL_PROFILE = "GET_DEV_PROD_CENTRAL_PROFILE";
export const PUT_DEV_PROD_CENTRAL_PROFILE = "PUT_DEV_PROD_CENTRAL_PROFILE";

export const NO_ACTION = "NO_ACTION";
