import {
  BULLSEYE_REPORTS,
  COVERITY_REPORTS,
  ISSUE_MANAGEMENT_REPORTS,
  JENKINS_REPORTS,
  JIRA_MANAGEMENT_TICKET_REPORT,
  MICROSOFT_REPORT,
  NCC_GROUP_REPORTS,
  PAGERDUTY_REPORT,
  PRAETORIAN_REPORTS,
  SCM_DORA_REPORTS,
  SCM_REPORTS,
  SUPPORT_REPORTS,
  SALESFORCE_REPORTS,
  ZENDESK_REPORTS,
  SNYK_REPORTS,
  SONARQUBE_REPORTS,
  TESTRAILS_REPORTS,
  DORA_REPORTS,
  LEAD_MTTR_DORA_REPORTS
} from "dashboard/constants/applications/names";

const ALLOWED_JIRA_REPORTS_FOR_FILTER_CONFIG: Array<JIRA_MANAGEMENT_TICKET_REPORT> = [
  JIRA_MANAGEMENT_TICKET_REPORT.BOUNCE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.HOPS_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.RESPONSE_TIME_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.FIRST_ASSIGNEE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.RESOLUTION_TIME_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.TICKETS_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.ASSIGNEE_TIME_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.HYGIENE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.BOUNCE_REPORT_TRENDS,
  JIRA_MANAGEMENT_TICKET_REPORT.BOUNCE_COUNT_STAT,
  JIRA_MANAGEMENT_TICKET_REPORT.TIME_ACROSS_STAGES,
  JIRA_MANAGEMENT_TICKET_REPORT.BACKLOG_TREND_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.SPRINT_METRICS_SINGLE_STAT,
  JIRA_MANAGEMENT_TICKET_REPORT.SPRINT_METRICS_PERCENTAGE_TREND,
  JIRA_MANAGEMENT_TICKET_REPORT.SPRINT_METRICS_TREND,
  JIRA_MANAGEMENT_TICKET_REPORT.SPRINT_GOAL,
  JIRA_MANAGEMENT_TICKET_REPORT.EFFORT_INVESTMENT_SINGLE_STAT_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.EFFORT_INVESTMENT_ENGINEER_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.EFFORT_INVESTMENT_ALIGNMENT_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.EFFORT_INVESTMENT_TREND_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.PROGRESS_SINGLE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.HOPS_REPORT_TRENDS,
  JIRA_MANAGEMENT_TICKET_REPORT.HOPS_REPORT_SINGLE_STAT,
  JIRA_MANAGEMENT_TICKET_REPORT.RESPONSE_TIME_TREND_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.RESPONSE_TIME_SINGLE_STAT_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.RESOLUTION_TIME_TREND_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.RESOLUTION_TIME_SINGLE_STAT_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.TICKET_REPORT_TREND,
  JIRA_MANAGEMENT_TICKET_REPORT.TICKET_ISSUE_SINGLE_STAT,
  JIRA_MANAGEMENT_TICKET_REPORT.HYGIENE_REPORT_TREND,
  JIRA_MANAGEMENT_TICKET_REPORT.TICKET_COUNT_BY_FIRST_ASSIGNEE,
  JIRA_MANAGEMENT_TICKET_REPORT.SPRINT_IMPACT_ESTIMATED_TICKET_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.STAGE_BOUNCE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.STAGE_BOUNCE_SINGLE_STAT,
  JIRA_MANAGEMENT_TICKET_REPORT.SPRINT_DISTRIBUTION_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.LEAD_TIME_BY_STAGE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.LEAD_TIME_BY_TYPE_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.LEAD_TIME_TREND_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.ISSUE_LEAD_TIME_TREND_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.LEAD_TIME_BY_TIME_SPENT_IN_STAGES_REPORT,
  JIRA_MANAGEMENT_TICKET_REPORT.JIRA_RELEASE_TABLE_REPORT
];

const ALLOWED_SCM_REPORTS_FOR_FILTER_CONFIG: Array<SCM_REPORTS> = [
  SCM_REPORTS.PRS_SINGLE_STAT,
  SCM_REPORTS.COMMITS_SINGLE_STAT,
  SCM_REPORTS.PRS_MERGE_TRENDS,
  SCM_REPORTS.PRS_REPORT,
  SCM_REPORTS.PRS_FIRST_REVIEW_TRENDS,
  SCM_REPORTS.PRS_FIRST_REVIEW_TO_MERGE_TRENDS,
  SCM_REPORTS.ISSUES_REPORT,
  SCM_REPORTS.ISSUES_REPORT_TRENDS,
  SCM_REPORTS.ISSUES_COUNT_SINGLE_STAT,
  SCM_REPORTS.ISSUES_FIRST_RESPONSE_REPORT,
  SCM_REPORTS.ISSUES_FIRST_RESPONSE_TREND_REPORT,
  SCM_REPORTS.ISSUES_FIRST_RESPONSE_COUNT_SINGLE_STAT,
  SCM_REPORTS.PRS_MERGE_SINGLE_STAT,
  SCM_REPORTS.PRS_FIRST_REVIEW_SINGLE_STAT,
  SCM_REPORTS.PRS_FIRST_REVIEW_MERGE_SINGLE_STAT,
  SCM_REPORTS.REPOS_REPORT,
  SCM_REPORTS.COMMITTERS_REPORT,
  SCM_REPORTS.ISSUES_TIME_RESOLUTION_REPORT,
  SCM_REPORTS.PR_LEAD_TIME_TREND_REPORT,
  SCM_REPORTS.PR_LEAD_TIME_BY_STAG_REPORT,
  SCM_REPORTS.CODING_DAYS_REPORT,
  SCM_REPORTS.CODING_DAYS_SINGLE_STAT,
  SCM_REPORTS.PRS_RESPONSE_TIME_REPORT,
  SCM_REPORTS.COMMITS_REPORT,
  SCM_REPORTS.SCM_FILES_REPORT,
  SCM_REPORTS.ISSUES_FIRST_RESPONSE_REPORT_TRENDS,
  SCM_REPORTS.SCM_JIRA_FILES_REPORT,
  SCM_REPORTS.FILE_TYPES_REPORT,
  SCM_REPORTS.SCM_REVIEW_COLLABORATION_REPORT,
  SCM_REPORTS.REWORK_REPORT,
  SCM_REPORTS.SCM_PRS_RESPONSE_TIME_SINGLE_STAT,
  SCM_REPORTS.SCM_TIME_ACROSS_STAGES
];

const ALLOWED_ZENDESK_REPORT_FOR_FILTER_CONFIG: Array<SUPPORT_REPORTS | ZENDESK_REPORTS> = [
  SUPPORT_REPORTS.ZENDESK_BOUNCE_REPORT,
  SUPPORT_REPORTS.ZENDESK_HOPS_REPORT,
  ZENDESK_REPORTS.ZENDESK_RESPONSE_TIME_REPORT,
  SUPPORT_REPORTS.ZENDESK_RESOLUTION_TIME_REPORT,
  SUPPORT_REPORTS.ZENDESK_TICKETS_REPORT,
  SUPPORT_REPORTS.ZENDESK_HYGIENE_REPORT,
  ZENDESK_REPORTS.ZENDESK_REOPENS_REPORT,
  ZENDESK_REPORTS.ZENDESK_REPLIES_REPORT,
  ZENDESK_REPORTS.ZENDESK_AGENT_WAIT_TIME_REPORT,
  ZENDESK_REPORTS.ZENDESK_REQUESTER_WAIT_TIME_REPORT,
  ZENDESK_REPORTS.ZEKDESK_BOUNCE_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_HOPS_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_RESOLUTION_TIME_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_TICKETS_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_HYGIENE_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_REQUESTER_WAIT_TIME_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_AGENT_WAIT_TIME_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_REPLIES_REPORT_TRENDS,
  ZENDESK_REPORTS.ZENDESK_REOPENS_REPORT_TRENDS,
  SUPPORT_REPORTS.ZENDESK_TOP_CUSTOMERS_REPORT,
  ZENDESK_REPORTS.ZENDESK_RESPONSE_TIME_TREND_REPORT
];

const ALLOWED_JIRA_ZENDESK_REPORTS_FILTER_CONFIG: Array<SUPPORT_REPORTS> = [
  SUPPORT_REPORTS.JIRA_ZENDESK_FILES_REPORT,
  SUPPORT_REPORTS.JIRA_ZENDESK_ESCALATION_TIME_REPORT,
  SUPPORT_REPORTS.ZENDESK_C2F_TRENDS,
  SUPPORT_REPORTS.ZENDESK_TIME_ACROSS_STAGES
];

const ALLOWED_JIRA_SALESFORCE_REPORTS_FOR_FILTER_CONFIG: Array<SUPPORT_REPORTS> = [
  SUPPORT_REPORTS.JIRA_SALESFORCE_ESCALATION_TIME_REPORT,
  SUPPORT_REPORTS.SALESFORCE_C2F_TRENDS,
  SUPPORT_REPORTS.JIRA_SALESFORCE_FILES_REPORT,
  SUPPORT_REPORTS.SALESFORCE_TIME_ACROSS_STAGES
];
const ALLOWED_TESTRAILS_REPORTS_FOR_FILTER_CONFIG: Array<TESTRAILS_REPORTS> = [
  TESTRAILS_REPORTS.TESTRAILS_TESTS_REPORT,
  TESTRAILS_REPORTS.TESTRAILS_TESTS_TRENDS_REPORT,
  TESTRAILS_REPORTS.TESTRAILS_TESTS_ESTIMATE_REPORT,
  TESTRAILS_REPORTS.TESTRAILS_TESTS_ESTIMATE_TRENDS_REPORT,
  TESTRAILS_REPORTS.TESTRAILS_TESTS_ESTIMATE_FORECAST_REPORT,
  TESTRAILS_REPORTS.TESTRAILS_TESTS_ESTIMATE_FORECAST_TRENDS_REPORT
];

const ALLOWED_SONARQUBE_REPORTS_FOR_FILTER_CONFIG: Array<SONARQUBE_REPORTS> = [
  SONARQUBE_REPORTS.SONARQUBE_ISSUES_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_EFFORT_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_ISSUES_REPORT_TRENDS,
  SONARQUBE_REPORTS.SONARQUBE_EFFORT_REPORT_TRENDS,
  SONARQUBE_REPORTS.SONARQUBE_METRICS_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_METRICS_TREND_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_CODE_COMPLEXITY_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_CODE_COMPLEXITY_TRENDS_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_CODE_DUPLICATION_REPORT,
  SONARQUBE_REPORTS.SONARQUBE_CODE_DUPLICATION_TREND_REPORT
];

const ALLOWED_PAGERDUTY_REPORTS_FOR_FILTER_CONFIG: Array<PAGERDUTY_REPORT> = [
  PAGERDUTY_REPORT.PAGERDUTY_HOTSPOT_REPORT,
  PAGERDUTY_REPORT.PAGERDUTY_RELEASE_INCIDENT_REPORT,
  PAGERDUTY_REPORT.PAGERDUTY_ACK_TREND_REPORT,
  PAGERDUTY_REPORT.PAGERDUTY_AFTER_HOURS_REPORT,
  PAGERDUTY_REPORT.PAGERDUTY_INCIDENT_REPORT_TRENDS,
  PAGERDUTY_REPORT.RESPONSE_REPORTS
];

const ALLOWED_SNYK_REPORTS_FOR_FILTER_CONFIG: Array<SNYK_REPORTS> = [SNYK_REPORTS.SNYK_VULNERABILITY_REPORT];

const ALLOWED_AZURE_REPORTS_FOR_FILTER_CONFIG: Array<ISSUE_MANAGEMENT_REPORTS> = [
  ISSUE_MANAGEMENT_REPORTS.HOPS_REPORT_SINGLE_STAT,
  ISSUE_MANAGEMENT_REPORTS.RESOLUTION_TIME_TREND_REPORT,
  ISSUE_MANAGEMENT_REPORTS.TIME_ACROSS_STAGES,
  ISSUE_MANAGEMENT_REPORTS.BOUNCE_COUNT_STAT,
  ISSUE_MANAGEMENT_REPORTS.RESOLUTION_TIME_SINGLE_STAT_REPORT,
  ISSUE_MANAGEMENT_REPORTS.RESPONSE_TIME_TREND_REPORT,
  ISSUE_MANAGEMENT_REPORTS.RESPONSE_TIME_SINGLE_STAT_REPORT,
  ISSUE_MANAGEMENT_REPORTS.BACKLOG_TREND_REPORT,
  ISSUE_MANAGEMENT_REPORTS.SPRINT_METRICS_TREND,
  ISSUE_MANAGEMENT_REPORTS.SPRINT_METRICS_PERCENTAGE_TREND,
  ISSUE_MANAGEMENT_REPORTS.EFFORT_INVESTMENT_ALIGNMENT_REPORT,
  ISSUE_MANAGEMENT_REPORTS.EFFORT_INVESTMENT_ENGINEER_REPORT,
  ISSUE_MANAGEMENT_REPORTS.EFFORT_INVESTMENT_SINGLE_STAT_REPORT,
  ISSUE_MANAGEMENT_REPORTS.EFFORT_INVESTMENT_TREND_REPORT,
  ISSUE_MANAGEMENT_REPORTS.RESPONSE_TIME_REPORT,
  ISSUE_MANAGEMENT_REPORTS.RESOLUTION_TIME_REPORT,
  ISSUE_MANAGEMENT_REPORTS.BOUNCE_REPORT,
  ISSUE_MANAGEMENT_REPORTS.BOUNCE_REPORT_TRENDS,
  ISSUE_MANAGEMENT_REPORTS.FIRST_ASSIGNEE_REPORT,
  ISSUE_MANAGEMENT_REPORTS.TICKETS_REPORT,
  ISSUE_MANAGEMENT_REPORTS.TICKET_REPORT_TREND,
  ISSUE_MANAGEMENT_REPORTS.TICKET_ISSUE_SINGLE_STAT,
  ISSUE_MANAGEMENT_REPORTS.HOPS_REPORT,
  ISSUE_MANAGEMENT_REPORTS.HOPS_REPORT_TRENDS,
  ISSUE_MANAGEMENT_REPORTS.HYGIENE_REPORT,
  ISSUE_MANAGEMENT_REPORTS.HYGIENE_REPORT_TREND,
  ISSUE_MANAGEMENT_REPORTS.SPRINT_METRICS_SINGLE_STAT,
  ISSUE_MANAGEMENT_REPORTS.STAGE_BOUNCE_REPORT,
  ISSUE_MANAGEMENT_REPORTS.ISSUE_LEAD_TIME_TREND_REPORT,
  ISSUE_MANAGEMENT_REPORTS.LEAD_TIME_SINGLE_STAT,
  ISSUE_MANAGEMENT_REPORTS.SPRINT_IMPACT_ESTIMATED_TICKET_REPORT,
  ISSUE_MANAGEMENT_REPORTS.ISSUE_LEAD_TIME_BY_TYPE_REPORT,
  ISSUE_MANAGEMENT_REPORTS.ISSUE_LEAD_TIME_BY_STAGE_REPORT,
  ISSUE_MANAGEMENT_REPORTS.STAGE_BOUNCE_SINGLE_STAT,
  ISSUE_MANAGEMENT_REPORTS.AZURE_ISSUES_PROGRESS_REPORT,
  ISSUE_MANAGEMENT_REPORTS.AZURE_PROGRAM_PROGRESS_REPORT
];

const ALLOWED_BULLSEYE_REPORTS_FOR_FILTER_CONFIG: Array<BULLSEYE_REPORTS> = [
  BULLSEYE_REPORTS.BULLSEYE_BRANCH_COVERAGE_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_BRANCH_COVERAGE_TREND_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_CODE_COVERAGE_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_CODE_COVERAGE_TREND_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_DECISION_COVERAGE_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_DECISION_COVERAGE_TREND_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_FUNCTION_COVERAGE_REPORT,
  BULLSEYE_REPORTS.BULLSEYE_FUNCTION_COVERAGE_TREND_REPORT
];

const ALLOWED_COVERITY_REPORTS_FOR_FILTER_CONFIG: Array<COVERITY_REPORTS> = [
  COVERITY_REPORTS.COVERITY_ISSUE_REPORT,
  COVERITY_REPORTS.COVERITY_ISSUE_STAT_REPORT,
  COVERITY_REPORTS.COVERITY_ISSUE_TREND_REPORT
];

const ALLOWED_PRAETORIAN_REPORTS_FOR_FILTER_CONFIG: Array<PRAETORIAN_REPORTS> = [
  PRAETORIAN_REPORTS.PRAETORIAN_ISSUES_REPORT
];

const ALLOWED_MICROSOFT_REPORTS_FOR_FILTER_CONFIG: Array<MICROSOFT_REPORT> = [
  MICROSOFT_REPORT.MICROSOFT_ISSUES_REPORT_NAME
];

const ALLOWED_SALESFORCE_REPORTS_FOR_FILTER_CONFIG: Array<SALESFORCE_REPORTS> = [
  SALESFORCE_REPORTS.SALESFORCE_BOUNCE_REPORT,
  SALESFORCE_REPORTS.SALESFORCE_HOPS_REPORT,
  SALESFORCE_REPORTS.SALESFORCE_RESOLUTION_TIME_REPORT,
  SALESFORCE_REPORTS.SALESFORCE_TICKETS_REPORT,
  SALESFORCE_REPORTS.SALESFORCE_HYGIENE_REPORT,
  SALESFORCE_REPORTS.SALESFORCE_TICKETS_REPORT_TRENDS,
  SALESFORCE_REPORTS.SALESFORCE_TOP_CUSTOMERS_REPORT
];

const ALLOWED_NCC_GROUP_REPORTS_FOR_FILTER_CONFIG: Array<NCC_GROUP_REPORTS> = [NCC_GROUP_REPORTS.VULNERABILITY_REPORT];

const ALLOWED_SCM_DORA_REPORTS_FOR_FILTER_CONFIG: Array<SCM_DORA_REPORTS> = [
  SCM_DORA_REPORTS.LEAD_TIME_FOR_CHNAGE,
  SCM_DORA_REPORTS.DEPLOYMENT_FREQUENCY,
  SCM_DORA_REPORTS.TIME_TO_RECOVER,
  SCM_DORA_REPORTS.FAILURE_RATE
];
const ALLOWED_JENKINS_REPORTS_FOR_FILTERS_CONFIG: Array<JENKINS_REPORTS> = [
  JENKINS_REPORTS.JOB_CONFIG_CHANGE_COUNTS_STAT,
  JENKINS_REPORTS.JOB_CONFIG_CHANGE_COUNTS,
  JENKINS_REPORTS.JOB_CONFIG_CHANGE_COUNTS_TREND,
  JENKINS_REPORTS.JENKINS_COUNT_SINGLE_STAT_REPORT,
  JENKINS_REPORTS.JOBS_COMMITS_LEAD_SINGLE_STAT_REPORT,
  JENKINS_REPORTS.JOBS_DURATION_SINGLE_STAT_REPORT,
  JENKINS_REPORTS.JOBS_CHANGE_VOLUMES_SINGLE_STAT_REPORT,
  JENKINS_REPORTS.CICD_SCM_JOBS_DURATION_REPORT,
  JENKINS_REPORTS.CICD_PIPELINE_JOBS_DURATION_REPORT,
  JENKINS_REPORTS.CICD_PIPELINE_JOBS_DURATION_TREND_REPORT,
  JENKINS_REPORTS.CICD_JOBS_COUNT_REPORT,
  JENKINS_REPORTS.CICD_PIPELINE_JOBS_COUNT_REPORT,
  JENKINS_REPORTS.CICD_PIPELINE_JOBS_COUNT_TREND_REPORT,
  JENKINS_REPORTS.JOBS_COUNT_TRENDS_REPORT,
  JENKINS_REPORTS.JOBS_DURATIONS_TRENDS_REPORT,
  JENKINS_REPORTS.JOBS_CHANGE_VOLUMES_TRENDS_REPORT,
  JENKINS_REPORTS.JOB_RUNS_TEST_REPORT,
  JENKINS_REPORTS.JOB_RUNS_TEST_TREND_REPROT,
  JENKINS_REPORTS.JOB_RUNS_TEST_DURATION_REPORT,
  JENKINS_REPORTS.JOB_RUNS_TEST_DURATION_TREND_REPROT,
  JENKINS_REPORTS.CODE_VOLUME_VS_DEPLOYMENT_REPORT,
  JENKINS_REPORTS.JOBS_COMMIT_LEADS_TRENDS_REPORT
];

const ALLOWED_DORA_REPORTS_FOR_FILTERS_CONFIG: Array<DORA_REPORTS> = [
  DORA_REPORTS.DEPLOYMENT_FREQUENCY_REPORT,
  DORA_REPORTS.CHANGE_FAILURE_RATE,
  DORA_REPORTS.LEADTIME_CHANGES,
  DORA_REPORTS.MEANTIME_RESTORE
];

const ALLOWED_DORA_LEAD_TIME_MTTR_CONFIG: Array<LEAD_MTTR_DORA_REPORTS> = [
  LEAD_MTTR_DORA_REPORTS.LEAD_TIME_FOR_CHANGE,
  LEAD_MTTR_DORA_REPORTS.MEAN_TIME_TO_RESTORE
];
export const ALLOWED_REPORTS_FOR_FILTER_CONFIG: Array<
  | JIRA_MANAGEMENT_TICKET_REPORT
  | ISSUE_MANAGEMENT_REPORTS
  | SCM_REPORTS
  | BULLSEYE_REPORTS
  | COVERITY_REPORTS
  | PRAETORIAN_REPORTS
  | MICROSOFT_REPORT
  | NCC_GROUP_REPORTS
  | SCM_DORA_REPORTS
  | SUPPORT_REPORTS
  | SALESFORCE_REPORTS
  | ZENDESK_REPORTS
  | JENKINS_REPORTS
  | TESTRAILS_REPORTS
  | SONARQUBE_REPORTS
  | PAGERDUTY_REPORT
  | SNYK_REPORTS
  | DORA_REPORTS
  | LEAD_MTTR_DORA_REPORTS
> = [
  ...ALLOWED_JIRA_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_COVERITY_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_BULLSEYE_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_AZURE_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_PRAETORIAN_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_MICROSOFT_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_NCC_GROUP_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_SCM_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_SCM_DORA_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_JIRA_ZENDESK_REPORTS_FILTER_CONFIG,
  ...ALLOWED_SALESFORCE_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_JIRA_SALESFORCE_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_ZENDESK_REPORT_FOR_FILTER_CONFIG,
  ...ALLOWED_JENKINS_REPORTS_FOR_FILTERS_CONFIG,
  ...ALLOWED_TESTRAILS_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_SONARQUBE_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_PAGERDUTY_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_SNYK_REPORTS_FOR_FILTER_CONFIG,
  ...ALLOWED_DORA_REPORTS_FOR_FILTERS_CONFIG,
  ...ALLOWED_DORA_LEAD_TIME_MTTR_CONFIG
];
