import { API_REQUIREMENTS } from "./types";

export const OU_OPTIONS_PIVOT_LIST = "OU_OPTIONS_PIVOT_LIST";
export const OU_OPTIONS_PIVOT_LIST_COMPLETE = "OU_OPTIONS_PIVOT_LIST_COMPLETE";

export const SCM_COMMITTER_FILTERS_SUPPORTED_APPLICATION = [
  "azure_devops",
  "github",
  "gitlab",
  "bitbucket_server",
  "gerrit",
  "helix"
];
export const SCM_SUPPORTED_FILTERS = ["reviewers", "assignees", "approvers", "creators"];
export const COMMITTER_SUPPORTER_FILTERS = ["authors", "committers"];
export const SCM_FIELDS = ["reviewer", "assignee", "approver", "creator"];
export const COMMITTER_FIELDS = ["author", "committer"];

export const API_FILTER_REQUIREMENT_INITIAL_STATE = {
  [API_REQUIREMENTS.JIRA_CUSTOM_FIELDS_REQUIRED]: false,
  [API_REQUIREMENTS.AZURE_CUSTOM_FIELD_REQUIRED]: false,
  [API_REQUIREMENTS.JIRA_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.AZURE_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.AZURE_SCM_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.AZURE_COMMITTERS_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.GITHUB_SCM_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.GITHUB_COMMITTERS_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.GITLAB_COMMITTERS_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.GITLAB_SCM_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.BITBUCKET_SCM_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.BITBUCKET_COMMITTER_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.GERRIT_SCM_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.GERRIT_COMMITTER_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.PAGERDUTY_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.HELIX_SCM_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.HELIX_COMMITTER_API_FILTER_REQUIRED]: false,
  [API_REQUIREMENTS.USERS_API_REQUIREMENT]: false
};
