
# Stage 3 - the production environment
FROM nginx:alpine as deploy
LABEL ui-stage=deploy
RUN mkdir /opt/scripts
COPY ./dist /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/nginx.conf
COPY ./deploy /opt/scripts
RUN chmod 777 /opt/scripts/*.sh
RUN ls -l /usr/share/nginx/html/
EXPOSE 80
ENTRYPOINT ["./opt/scripts/cmd.sh"]
